Group2/config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  get '/cart' => 'cart#index'

  root 'home#home'
  resources :products
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :charges
  resources :purchases
  resources :inventories
  resources :budgets
  resources :alerts


  get '/audit/note/' => 'audit#note'
  get '/audit/correct/' => 'audit#correct'
  get '/audit/request_doc/' => 'audit#request_doc'
  
  get '/alerts' => 'alerts#index'
  get '/alerts/new' => 'alerts#new'
  post 'alerts' => 'alerts#create'

  resources :users
  resources :conversations do
    resources :messages
  end
  

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'



end

Group2/app/models/access_audit.rb
class AccessAudit < ActiveRecord::Base
end

Group2/app/models/alert.rb
class Alert < ActiveRecord::Base

  
end

Group2/app/models/budget_manage.rb
class BudgetManage < ActiveRecord::Base
end

Group2/app/models/inventory.rb
class Inventory < ActiveRecord::Base
end

Group2/app/models/product.rb
class Product < ActiveRecord::Base
end

Group2/app/models/purchase.rb
class Purchase < ActiveRecord::Base
  has_many :receipts
end

Group2/app/models/receipt.rb
class Receipt < ActiveRecord::Base
  belongs_to :purchase
end

Group2/app/models/role.rb
class Role < ActiveRecord::Base
end

Group2/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_types
  acts_as_messageable

  def mailboxer_email(object)
    self.email
  end
end

Group2/app/models/user_type.rb
class UserType < ActiveRecord::Base
  belongs_to :user
  has_many :roles
end

Group2/app/models/user_type_role.rb
class UserTypeRole < ActiveRecord::Base
  belongs_to :user_type
  belongs_to :role
end

Group2/app/helpers/alerts_helper.rb
module AlertsHelper
end

Group2/app/helpers/audit_helper.rb
module AuditHelper
end

Group2/app/helpers/budgets_helper.rb
module BudgetsHelper
end

Group2/app/helpers/cart_helper.rb
module CartHelper
end

Group2/app/helpers/charges_helper.rb
module ChargesHelper
end

Group2/app/helpers/home_helper.rb
module HomeHelper
  
end

Group2/app/helpers/messages_helper.rb
module MessagesHelper
end

Group2/app/helpers/products_helper.rb
module ProductsHelper
end

Group2/app/helpers/users_helper.rb
module UsersHelper
end

Group2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Group2" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>


    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'HOME', '/' %></li>
        <% if user_signed_in? %>
            <li><%= link_to "Messages", conversations_path%></li>
            <% case current_user.user_type_id
                 when 1%>
                <li><%= link_to 'Create New User', new_user_path %></li>
                <li><%= link_to 'Manage Users', users_path %></li>
                <li><%= link_to 'Manage Budget', '/budgets/new' %></li>
            <% when 2 %>
                <li><%= link_to 'Manage Agent\'s Budget', 'budgets/new' %></li>
                <li><%= link_to 'Manage Users that are Watchers', users_path %></li>
            <% when 3 %>
                <li><%= link_to 'View Purchases', purchases_path %></li>

            <% when 4 %>
                <li><%= link_to 'Products', products_path %></li>
                <li><%= link_to 'Cart', '/cart' %></li>

            <% when 5 %>
                <li><%= link_to 'View Transactions', charges_path %></li>
            <% when 6 %>

                <li><%= link_to 'Send Alert', '/alerts/new' %></li>


                <li><%= link_to 'Request Document', '/audit/request_doc' %></li>


            <% when 7 %>
                <li><%= link_to 'Products', products_path %></li>
                <li><%= link_to 'Users', '/users/new' %></li>

            <% else %>
                <p></p>
            <%  end %>
            </ul>
            <ul class="nav navbar-nav", style="float:right">
              <li><%= link_to "Sign Out", destroy_user_session_path%></li>
            </ul>
        <% else %>
            </ul>
            <ul class="nav navbar-nav", style="float:right">
              <li><%= link_to "Sign In", new_user_session_path%></li>
            </ul>

        <% end %>
        </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>
</div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <%= yield %>
    </div>
    <div class="col-lg-3">
    </div><!--/span-->
  </div><!--/row-->
</div> <!-- /container -->








</body>
</html>