Group2/config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  get '/cart' => 'cart#index'

  root 'home#home'
  resources :products
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :charges
  resources :purchases
  resources :inventories
  resources :budgets
  resources :alerts


  get '/audit/note/' => 'audit#note'
  get '/audit/correct/' => 'audit#correct'
  get '/audit/request_doc/' => 'audit#request_doc'
  
  get '/alerts' => 'alerts#index'
  get '/alerts/new' => 'alerts#new'
  post 'alerts' => 'alerts#create'

  resources :users
  resources :conversations do
    resources :messages
  end
  

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'



end

Group2/app/models/access_audit.rb
class AccessAudit < ActiveRecord::Base
end

Group2/app/models/alert.rb
class Alert < ActiveRecord::Base

  
end

Group2/app/models/budget_manage.rb
class BudgetManage < ActiveRecord::Base
end

Group2/app/models/inventory.rb
class Inventory < ActiveRecord::Base
end

Group2/app/models/product.rb
class Product < ActiveRecord::Base
end

Group2/app/models/purchase.rb
class Purchase < ActiveRecord::Base
  has_many :receipts
end

Group2/app/models/receipt.rb
class Receipt < ActiveRecord::Base
  belongs_to :purchase
end

Group2/app/models/role.rb
class Role < ActiveRecord::Base
end

Group2/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_types
  acts_as_messageable

  def mailboxer_email(object)
    self.email
  end
end

Group2/app/models/user_type.rb
class UserType < ActiveRecord::Base
  belongs_to :user
  has_many :roles
end

Group2/app/models/user_type_role.rb
class UserTypeRole < ActiveRecord::Base
  belongs_to :user_type
  belongs_to :role
end

Group2/app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @conversations = current_user.mailbox.conversations
  end

  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
  end

  def new
    @recipients = User.all - [current_user]
  end

  def create
    recipient = User.find(params[:user_id])
    receipt = current_user.send_message(recipient, params[:body], params[:subject])
    redirect_to conversation_path(receipt.conversation)
  end
end

Group2/app/helpers/alerts_helper.rb
module AlertsHelper
end

Group2/app/helpers/audit_helper.rb
module AuditHelper
end

Group2/app/helpers/budgets_helper.rb
module BudgetsHelper
end

Group2/app/helpers/cart_helper.rb
module CartHelper
end

Group2/app/helpers/charges_helper.rb
module ChargesHelper
end

Group2/app/helpers/conversations_helper.rb
module ConversationsHelper
end

Group2/app/helpers/home_helper.rb
module HomeHelper
  
end

Group2/app/helpers/messages_helper.rb
module MessagesHelper
end

Group2/app/helpers/products_helper.rb
module ProductsHelper
end

Group2/app/helpers/users_helper.rb
module UsersHelper
end

Group2/app/views/conversations/_form.html.erb
<%= form_for conversation_messages_path(@conversation), do |f| %>
  <div>
    <%= f.text_area :body %>
  </div>
  <%= f.submit "Send" %>
<% end %>

Group2/app/views/conversations/index.html.erb
<h1>My Conversations</h1>

<% @conversations.each do |c| %>
  <div>
    <%= link_to c.subject, conversation_path(c)%>
  </div>

<% end %>

<%= link_to "New Conversation", new_conversation_path %>

<p> </p>

Group2/app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= form_tag conversations_path, method: :post do %>
  <div class="container">
    <div>
      <%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :name) %>
    </div>
    <div>
      <%= text_field_tag :subject, nil, placeholder: "Subject"%>
    </div>
    <div>
      <%= text_area_tag :body, nil, placeholder: "Message"%>
    </div>




  </div>
  <%= submit_tag "Send" %>
<% end %>

Group2/app/views/conversations/show.html.erb
<%= stylesheet_link_tag    "conversation", :media => "all", 'data-turbolinks-track' => true  %>
<div class="main">
<h1><%= @conversation.subject %></h1>

  <%@conversation.receipts_for(current_user).each do |r|%>
    <% if r.message.sender == current_user %>
      <div class='sent'>
        <p><%= r.message.sender.email%></p>
        <p><%= r.message.body %></p>
      </div>
    <% else %>
      <div class='received'>
        <p><%= r.message.sender.email%></p>
        <p><%= r.message.body %></p>
      </div>
    <% end %>
  <% end %>

<%= form_tag conversation_messages_path(@conversation), method: :post do %>
  <div>
    <%= text_area_tag :body%>
  </div>
  <%= submit_tag "Send"%>
<% end %>
</div>