Group2/config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  get '/cart' => 'cart#index'

  root 'home#home'
  resources :products
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :charges
  resources :purchases
  resources :inventories
  resources :budgets
  resources :alerts


  get '/audit/note/' => 'audit#note'
  get '/audit/correct/' => 'audit#correct'
  get '/audit/request_doc/' => 'audit#request_doc'
  
  get '/alerts' => 'alerts#index'
  get '/alerts/new' => 'alerts#new'
  post 'alerts' => 'alerts#create'

  resources :users
  resources :conversations do
    resources :messages
  end
  

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'



end

Group2/app/models/access_audit.rb
class AccessAudit < ActiveRecord::Base
end

Group2/app/models/alert.rb
class Alert < ActiveRecord::Base

  
end

Group2/app/models/budget_manage.rb
class BudgetManage < ActiveRecord::Base
end

Group2/app/models/inventory.rb
class Inventory < ActiveRecord::Base
end

Group2/app/models/product.rb
class Product < ActiveRecord::Base
end

Group2/app/models/purchase.rb
class Purchase < ActiveRecord::Base
  has_many :receipts
end

Group2/app/models/receipt.rb
class Receipt < ActiveRecord::Base
  belongs_to :purchase
end

Group2/app/models/role.rb
class Role < ActiveRecord::Base
end

Group2/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_types
  acts_as_messageable

  def mailboxer_email(object)
    self.email
  end
end

Group2/app/models/user_type.rb
class UserType < ActiveRecord::Base
  belongs_to :user
  has_many :roles
end

Group2/app/models/user_type_role.rb
class UserTypeRole < ActiveRecord::Base
  belongs_to :user_type
  belongs_to :role
end

Group2/app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:name, :description, :price, :stock)
    end
end

Group2/app/helpers/alerts_helper.rb
module AlertsHelper
end

Group2/app/helpers/audit_helper.rb
module AuditHelper
end

Group2/app/helpers/budgets_helper.rb
module BudgetsHelper
end

Group2/app/helpers/cart_helper.rb
module CartHelper
end

Group2/app/helpers/charges_helper.rb
module ChargesHelper
end

Group2/app/helpers/home_helper.rb
module HomeHelper
  
end

Group2/app/helpers/inventories_helper.rb
module InventoriesHelper
end

Group2/app/helpers/messages_helper.rb
module MessagesHelper
end

Group2/app/helpers/products_helper.rb
module ProductsHelper
end

Group2/app/helpers/purchases_helper.rb
module PurchasesHelper
end

Group2/app/helpers/users_helper.rb
module UsersHelper
end

Group2/app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Group2/app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

Group2/app/views/inventories/index.html.erb
<%- model_class = Inventory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:stock) %></th>
      <th><%= model_class.human_attribute_name(:item_number) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= link_to inventory.id, inventory_path(inventory) %></td>
        <td><%= inventory.name %></td>
        <td><%= inventory.description %></td>
        <td><%= inventory.price %></td>
        <td><%= inventory.stock %></td>
        <td><%= inventory.item_number %></td>
        <td><%= inventory.image %></td>
        <td><%=l inventory.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_inventory_path(inventory), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      inventory_path(inventory),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_inventory_path,
            :class => 'btn btn-primary' %>

Group2/app/views/inventories/new.html.erb
<%- model_class = Inventory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

Group2/app/views/inventories/show.html.erb
<%- model_class = Inventory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @inventory.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @inventory.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @inventory.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stock) %>:</strong></dt>
  <dd><%= @inventory.stock %></dd>
  <dt><strong><%= model_class.human_attribute_name(:item_number) %>:</strong></dt>
  <dd><%= @inventory.item_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @inventory.image %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              inventories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_inventory_path(@inventory), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              inventory_path(@inventory),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>