Group2/config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  get '/cart' => 'cart#index'

  root 'home#home'
  resources :products
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :charges
  resources :purchases
  resources :inventories
  resources :budgets
  resources :alerts


  get '/audit/note/' => 'audit#note'
  get '/audit/correct/' => 'audit#correct'
  get '/audit/request_doc/' => 'audit#request_doc'
  
  get '/alerts' => 'alerts#index'
  get '/alerts/new' => 'alerts#new'
  post 'alerts' => 'alerts#create'

  resources :users
  resources :conversations do
    resources :messages
  end
  

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'



end

Group2/app/models/access_audit.rb
class AccessAudit < ActiveRecord::Base
end

Group2/app/models/alert.rb
class Alert < ActiveRecord::Base

  
end

Group2/app/models/budget_manage.rb
class BudgetManage < ActiveRecord::Base
end

Group2/app/models/inventory.rb
class Inventory < ActiveRecord::Base
end

Group2/app/models/product.rb
class Product < ActiveRecord::Base
end

Group2/app/models/purchase.rb
class Purchase < ActiveRecord::Base
  has_many :receipts
end

Group2/app/models/receipt.rb
class Receipt < ActiveRecord::Base
  belongs_to :purchase
end

Group2/app/models/role.rb
class Role < ActiveRecord::Base
end

Group2/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_types
  acts_as_messageable

  def mailboxer_email(object)
    self.email
  end
end

Group2/app/models/user_type.rb
class UserType < ActiveRecord::Base
  belongs_to :user
  has_many :roles
end

Group2/app/models/user_type_role.rb
class UserTypeRole < ActiveRecord::Base
  belongs_to :user_type
  belongs_to :role
end

Group2/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!, :validate_user
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    #makes sure this page is available for the right user only
    def validate_user
      if user_signed_in?
        if !(current_user.user_type_id == 4 or current_user.user_type_id == 7 or
          current_user.user_type_id == 6)
          redirect_to root_path
        end
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
end

Group2/app/helpers/alerts_helper.rb
module AlertsHelper
end

Group2/app/helpers/application_helper.rb
module ApplicationHelper
end

Group2/app/helpers/audit_helper.rb
module AuditHelper
end

Group2/app/helpers/budgets_helper.rb
module BudgetsHelper
end

Group2/app/helpers/cart_helper.rb
module CartHelper
end

Group2/app/helpers/charges_helper.rb
module ChargesHelper
end

Group2/app/helpers/home_helper.rb
module HomeHelper
  
end

Group2/app/helpers/messages_helper.rb
module MessagesHelper
end

Group2/app/helpers/products_helper.rb
module ProductsHelper
end

Group2/app/helpers/purchases_helper.rb
module PurchasesHelper
end

Group2/app/helpers/users_helper.rb
module UsersHelper
end

Group2/app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product" } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>
  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :image, :class => 'form-control' %>
    </div>
    <%=f.error_span(:image) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

Group2/app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

Group2/app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>

    <tr>

      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>

        <td><%= link_to product.name, product_path(product) %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= image_tag product.image %></td>
        <% if current_user.user_type_id == 7%>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_product_path(product), :class => 'btn btn-default btn-xs' %></td>
            <td>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        product_path(product),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        <% end %>
        <% if current_user.user_type_id == 4 %>
          <td><a href= "/cart/<%= product.id %>"> Add to Cart </a></td>
        <% end %>


      </tr>
    <% end %>
  </tbody>
</table>
<% if current_user.user_type_id == 7%>
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>
<% end %>

Group2/app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

Group2/app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @product.image %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-default'  %>
<% if current_user.user_type_id == 7 %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_product_path(@product), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                product_path(@product),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
<% end %>